### ISSUE TITLE
[Dúvida Backend] Armazenamento em cache

### ISSUE THREAD

**Issue by Brunospo** [Impact-Plataform/Banco-de-talentos#12]
Olá, bom dia!! Vocês sabem informar o limite de Requests da API de cotações? Pois vi que na documentação que eles atualizam os valores a cada 30 segundos e gostaria de saber esse limite para ter uma ideia da frequência de atualização do cache da aplicação.

**Comment by MarioFLS** [comment]
Opa, bom dia!
Olha eu fiquei atualizando que nem um loco e deu em nada pra ser muito sincero, acredito que não de B.O ficar requisitando ela várias vezes. Acho que o a parte de fazer o Cache é muito mais para fins de estudo. 
Mas como vc disse, atualiza a cada 30s. ENtão não faz sentido um cache alto. EU deixei apenas 5 segundos se não me engano. Justamente por ser uma API feita pra ser requisitada muitas vezes

**Comment by Brunospo** [comment]
Ok, obrigado!!

**Comment by Brunospo** [comment]
Boa tarde, olha eu de novo!! É obrigatório retornar no endpoint de cotações o mesmo JSON da API <https://economia.awesomeapi.com.br/all> ou podemos filtrar somente os campos necessários?

Eu por exemplo, estou pensando em retornar apenas esses campos:

```json
{
   "code": "USD",
   "name": "Dólar Americano/Real Brasileiro",
   "ask": "5.2264",

}
```

**Comment by Arthuralentejo** [comment]
Pode sim filtar o que você quer retornar, desde que faça sentido para um possível usuário.
