### ISSUE TITLE
[Dúvida] - Rota /Currency

### ISSUE THREAD

**Issue by Joao-P-G-Begiato** [Impact-Plataform/Banco-de-talentos#16]
Prezados Bom dia.

Estou com uma dúvida referente ao enunciado o teste prático Backend.

a Minha dúvida é referente a essa parte:

Crie uma API REST, que responda os seguintes métodos:

[get] /Currency/ (todas as cotações)
[get] /Currency/$symbol (exemplo: BRL, USD, EUR)
   
   - Ao buscar o produto ele deverá vir com o valor cadastrador em Real e o valor equivalente em mais duas outras moedas da sua escolha (Ex: Dolar e EUR).

Em /Currency deve estar a cotação das moedas apenas, e quando buscar o produto em /Products através do GET o preço em duas outras moedas devem ser inseridos dinamicamente é isso?

Desde já agradeço a disposição e atenção.
João Paulo Gotardi Begiato

**Comment by Arthuralentejo** [comment]
Boa tarde João. 
É exatamente isso, você deve trazer o produto com o preço em outras moedas dinamicamente.
