### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by Brunospo** [Impact-Plataform/Banco-de-talentos#2]
Boa noite! Não entendi a parte do **POST Products/$ID** . Devemos cadastrar o produto e, ao invés de gerar o id pelo sistema ou pelo BD, enviar o id pela rota? Além disso, quais são os atributos que um produto deve ter ao ser cadastrado? Também não entendi a relação dos produtos com a cotação, ao buscar os produtos devemos retornar ele com todas as cotações?

**Comment by Arthuralentejo** [comment]
Bom dia Bruno. 
Desculpe a demora pra responder, corrigi algumas informações no documento que ficaram ambiguas, mas seus questionamentos estão corretos. 
O post de products não precisa de ID pois você está criando o produto. 
Sobre os atributos de um produto ao serem cadastrados, tirando o valor (que é necessário para o desafio) o resto fica a sua escolha do que achar relevante ter.
E sobre a cotação, na busca do produto (Get all e get/$id)  você deve trazer o produto com o seu valor cadastrado em reais e em mais duas cotações da sua escolha (Ex: EUR e USD)

**Comment by rodriigolima** [comment]
Me ajuda a entender bem querem uma api que cadastre um produto com resposta em json onde o preço desse produto deve retornar um outro json com o preço em BRL, USD, EUR?
