### ISSUE TITLE
[Front-end] - Funcionalidades

### ISSUE THREAD

**Issue by Joao-P-G-Begiato** [Impact-Plataform/Banco-de-talentos#21]
Olá Prezados, 
Estou com uma dúvida referente ao  que é solicitado no front-end.

os requisitos são:
  - Paginação para navegar entre os cartões
  - Informações adicionais ao clicar nos cartões dos personagens
  - Uma página interna com mais detalhes dos personagens (use sua criatividade);

o que fiz foi na pagina inicial ter um cartão para cada personagem contendo apenas o nome do mesmo, e ao clicar no nome o site navega para uma pagina inteira com detalhes do personagem (com navegação entre eles).

exemplo de cartão de personagem:
![image](https://user-images.githubusercontent.com/102306068/212217394-7441dfb8-ba18-407c-bcd0-df1246d65c86.png)

exemplo de pagina interna de personagem:
![image](https://user-images.githubusercontent.com/102306068/212217516-6843fdc4-ffe4-4c31-9272-fa66982fab6b.png)

resumindo os cartões estão como demonstrado na primeira imagem (exemplo de cartão de personagem) que ao clicar te leva para essa pagina interna conforme imagem 2 (exemplo de pagina interna).

isso cumpre os requisitos, ou teria que colocar a funcionalidade de mostrar mais informações nos cards e outra funcionalidade de navegar para uma pagina mais interna ?

**Comment by Arthuralentejo** [comment]
Desse jeito ja cumpre os requisitos do projeto.
