### ISSUE TITLE
Prazo de Entrega

### ISSUE THREAD

**Issue by antigo-icaroteles** [Impact-Plataform/Banco-de-talentos#4]
Olá, gostaria de confirmar qual o prazo máximo para a entrega do desafio.

**Comment by Impact-Plataform** [comment]
Bom dia Ícaro, tudo bem?

Você pode fazer e entregar quando for mais conveniente para você.

Na primeira semana de Janeiro teremos um webinar explicando tudo, você pode
fazer antes ou depois do webinar. Fique à vontade, tudo bem?


Atenciosamente,



*Equipe Plataforma Impact*
plataformatech.com <https://www.plataformatech.com/>
<https://wa.me/12067775134> <https://www.facebook.com/plataformaimpact>
<https://www.instagram.com/plataformaimpact/>
<https://www.linkedin.com/company/plataforma-impact/>
