### ISSUE TITLE
[Dúvida] - Alterar link da API

### ISSUE THREAD

**Issue by urielbochi** [Impact-Plataform/Banco-de-talentos#8]
Boa tarde, posso utilizar outra API para realizar o desafio front-end? Seria a mesma entrega, apenas utilizando outra API.

Em alguns momentos a API do Swapi fica muito lenta, o tempo de resposta dessa outra API é melhor. 

Outro fator é que ela possui a espécie "Human", diferente da Swapi que não possui. 

API em questão: https://swapi.py4e.com/api/people/

**Comment by Arthuralentejo** [comment]
Sem problemas. Pode usar essa outra api a vontade.
